server:
  port: 8072

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: sample
          uri: lb://sample
          predicates:
            - Path=/sample/**
          filters:
            - RewritePath=/sample/(?<path>.*), /$\{path}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8070/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"